
development:
  adapter: postgresql
  encoding: unicode
  database: mexican_development
  username: develop
  password: develop

test:
  adapter: postgresql
  encoding: unicode
  database: mexican_test
  pool: 5
  username: test
  password: test

production:
  adapter: postgresql
  encoding: unicode
  database: mexican_production
  pool: 5
  username: production
  password: production
